variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:1.29.2

services:
  - name: docker:dind
    alias: docker

stages:
  - build
  - deploy
  - cleanup

before_script:
  - docker version
  - docker-compose version

build_dev:
  stage: build
  script:
    - echo "DEMO build"
    - docker-compose -f docker-compose.demo.yml down
    - docker-compose -f docker-compose.demo.yml build
  only:
    - dev
  tags:
    - oaipmh

deploy_dev:
  stage: deploy
  script:
    - echo "DEMO deploy"
    - docker-compose -f docker-compose.demo.yml up -d
  only:
    - dev
  tags:
    - oaipmh

build_prod:
  stage: build
  script:
    - echo "PROD build"
    - docker-compose -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.prod.yml build
  only:
    - master
  tags:
    - oaipmh

deploy_prod:
  stage: build
  script:
    - echo "PROD deploy"
    - docker-compose -f docker-compose.prod.yml up -d
  only:
    - master
  tags:
    - oaipmh

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up the system"
    - docker system prune -a -f
  only:
    - dev
    - master
  tags:
    - oaipmh